site_name: FATEC PraGente
repo_url: https://github.com/olv-leo/fpg-curso
repo_name: olv-leo/fpg-curso
site_url: https://conteudo.fatecpragente.com.br


nav:
  - Home: index.md
  - Provas:
      - 2025 - 1º Semestre:
          - Questão 01: provas/2025-1-semestre/questao-01.md
  - Como passar na FATEC: 
    - Método: pilares-estudo/pilares-estudo.md
    - Planejamento: pilares-estudo/planejamento.md
    - Técnica: pilares-estudo/tecnica.md
    - Cabeça: pilares-estudo/cabeca.md
  - Matérias:
      - Português:
          - Pronomes:
              - Pronomes relativos: materias/portugues/pronomes/pronomes-relativos.md
          - Conjunções:
              - Conjunções integrantes: materias/portugues/conjuncoes/conjuncoes-integrantes.md
      - Matemática:
          - PA: materia/matematica/progressao-aritimetica.md


theme:
  name: material
  features:
    - announce.dismiss
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema claro
    - scheme: claro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para tema escuto
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  language: pt

# Additional configuration
plugins:
  - mkdocs_quiz
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.smartsymbols


